// Example TUI application.
//
// Run with:
//
//	go run ./tui/example
//
// Type anything and press Enter — the text is echoed back as an assistant message.
// Type / to open the command palette. Ctrl+C exits.
package main

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/paularlott/cli/tui"
)

func main() {
	var t *tui.TUI

	t = tui.New(tui.Config{
		StatusLeft:    "tui/example",
		StatusRight:   "Ctrl+C to exit",
		ShowCharCount: true,
		OnEscape: func() {
			if t.IsStreaming() {
				t.StopStreaming()
				t.AddMessage(tui.RoleSystem, "Stream cancelled")
			} else {
				t.AddMessage(tui.RoleSystem, "Escape pressed")
			}
		},
		Commands: []*tui.Command{
			{
				Name:        "exit",
				Description: "Exit the application",
				Handler:     func(_ string) { t.Exit() },
			},
			{
				Name:        "help",
				Description: "Show available commands",
				Handler: func(_ string) {
					// Collect commands from the palette via a local closure — we
					// just build the list from what we registered.
					var b strings.Builder
					b.WriteString("Available commands:\n")
					for _, c := range []*tui.Command{
						{Name: "exit", Description: "Exit the application"},
						{Name: "help", Description: "Show available commands"},
						{Name: "clear", Description: "Clear conversation history"},
						{Name: "status", Description: "Set the status bar message"},
						{Name: "theme", Description: "Switch theme"},
						{Name: "stream", Description: "Simulate a streaming LLM response"},
						{Name: "demo", Description: "Add a demo message with a code block"},
						{Name: "spinner", Description: "Show a spinner for 3 seconds"},
						{Name: "progress", Description: "Animate a progress bar to 100%"},
						{Name: "addmessageas", Description: "Add a message with a custom label"},
					} {
						b.WriteString(fmt.Sprintf("  /%-14s %s\n", c.Name, c.Description))
					}
					t.AddMessage(tui.RoleSystem, strings.TrimRight(b.String(), "\n"))
				},
			},
			{
				Name:        "clear",
				Description: "Clear conversation history",
				Handler:     func(_ string) { t.ClearOutput() },
			},
			{
				Name:        "status",
				Description: "Set the status bar message",
				Handler: func(args string) {
					t.SetStatus(args, "Ctrl+C to exit")
				},
			},
			{
				Name:        "theme",
				Description: "Switch theme: default | amber | blue | green | purple | light | plain",
				Args:        []string{"default", "amber", "blue", "green", "purple", "light", "plain"},
				Handler: func(args string) {
					theme, ok := tui.ThemeByName(args)
					if !ok {
						theme = tui.ThemeAmber
						args = "amber"
					}
					t.SetTheme(theme)
					t.AddMessage(tui.RoleSystem, "Theme switched to: "+args)
				},
			},
			{
				Name:        "stream",
				Description: "Simulate a streaming LLM response",
				Handler: func(_ string) {
					chunks := []string{
						"Streaming responses work by sending ",
						"tokens one at a time as they are ",
						"generated by the model.\n\n",
						"This allows the UI to update in real ",
						"time without waiting for the full ",
						"response to complete.\n\n",
						"Here is a code example:\n\n",
						"```go\n",
						"t.StartStreamingAs(\"GPT-4o\")\n",
						"for chunk := range stream {\n",
						"    t.StreamChunk(chunk)\n",
						"    t.Refresh()\n",
						"}\n",
						"t.StreamComplete()\n",
						"```\n\n",
						"Press Esc at any time to cancel the stream. ",
						"The partial response will be finalised ",
						"and displayed as-is.\n\n",
						"More text to demonstrate scrolling behaviour ",
						"as the output region fills up and new content ",
						"pushes older messages upward.\n",
					}
					go func() {
						t.StartStreamingAs("GPT-4o")
						for _, chunk := range chunks {
							if !t.IsStreaming() {
								return
							}
							t.StreamChunk(chunk)
							time.Sleep(80 * time.Millisecond)
						}
						if t.IsStreaming() {
							t.StreamComplete()
						}
					}()
				},
			},
			{
				Name:        "demo",
				Description: "Add a demo message with a code block",
				Handler: func(_ string) {
					t.AddMessage(tui.RoleAssistant, "Here is a Go snippet:\n\n```go\npackage main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, world!\")\n}\n```\n\nRun it with `go run main.go`.")
				},
			},
			{
				Name:        "spinner",
				Description: "Show a spinner for 3 seconds",
				Handler: func(_ string) {
					go func() {
						t.StartSpinner("Thinking…")
						time.Sleep(3 * time.Second)
						t.StopSpinner()
						t.AddMessage(tui.RoleSystem, "Spinner done.")
					}()
				},
			},
			{
				Name:        "progress",
				Description: "Animate a progress bar to 100%",
				Handler: func(_ string) {
					go func() {
						for i := 0; i <= 100; i++ {
							t.SetProgress("Loading…", float64(i)/100)
							time.Sleep(30 * time.Millisecond)
						}
						t.ClearProgress()
						t.AddMessage(tui.RoleSystem, "Progress complete.")
					}()
				},
			},
			{
				Name:        "addmessageas",
				Description: "Add a message with a custom label",
				Handler: func(_ string) {
					t.AddMessageAs(tui.RoleAssistant, "Custom Model", "Hello from a custom-labelled assistant message!")
				},
			},
			{
				Name:        "menu",
				Description: "Open a demo navigable menu",
				Handler: func(_ string) {
					t.OpenMenu(&tui.Menu{
						Title: "Settings",
						Items: []*tui.MenuItem{
							{
								Label: "Theme",
								Children: []*tui.MenuItem{
									{Label: "Amber", Value: "amber", OnSelect: func(item *tui.MenuItem, _ string) {
										if th, ok := tui.ThemeByName(item.Value); ok {
											t.SetTheme(th)
										}
									}},
									{Label: "Blue", Value: "blue", OnSelect: func(item *tui.MenuItem, _ string) {
										if th, ok := tui.ThemeByName(item.Value); ok {
											t.SetTheme(th)
										}
									}},
									{Label: "Default", Value: "default", OnSelect: func(item *tui.MenuItem, _ string) {
										if th, ok := tui.ThemeByName(item.Value); ok {
											t.SetTheme(th)
										}
									}},
								},
							},
							{
								Label: "Notifications",
								Children: []*tui.MenuItem{
									{
										Label:  "Email address",
										Prompt: "Enter email address:",
										OnSelect: func(_ *tui.MenuItem, input string) {
											t.AddMessage(tui.RoleSystem, "Email set to: "+input)
										},
									},
									{
										Label:  "Webhook URL",
										Prompt: "Enter webhook URL:",
										OnSelect: func(_ *tui.MenuItem, input string) {
											t.AddMessage(tui.RoleSystem, "Webhook set to: "+input)
										},
									},
								},
							},
							{
								Label: "About",
								OnSelect: func(_ *tui.MenuItem, _ string) {
									t.AddMessage(tui.RoleSystem, "tui/example — demo application")
								},
							},
						},
					})
				},
			},
		},
		OnSubmit: func(text string) {
			t.AddMessage(tui.RoleUser, text)
			t.AddMessage(tui.RoleAssistant, "Echo: "+text)
		},
	})

	t.AddMessage(tui.RoleSystem, "Welcome! Type anything and press Enter.\nType / for commands. Ctrl+C to exit.")

	if err := t.Run(context.Background()); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
